### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by Skallwar** [siddhantdubey/getdeletedtwitchvods#2]
I'm trying to download [this](https://www.twitch.tv/videos/800612525) deleted VOD by [this guy](https://www.twitch.tv/lowblowttv) at 2020-11-12 20:15:00 UTC

```
Enter streamer name: lowblowttv
Enter vod id: 800612525
Enter VOD timestamp (YYYY-MM-DD HH:MM:SS) UTC:  2020-11-12 20:15:00
https://vod-secure.twitch.tv/c2914f9b49f638cbfa5e_lowblowttv_800612525_1605212100/chunked/index-dvr.m3u8
```

VLC output when I try to open it:
```
Your input can't be opened:
VLC is unable to open the MRL 'Your input can't be opened:
VLC is unable to open the MRL 'https://vod-secure.twitch.tv/c2914f9b49f638cbfa5e_lowblowttv_800612525_1605212100/chunked/index-dvr.m3u8'. Check the log for details.
'. Check the log for details.
```

Am I missing something?

**Comment by siddhantdubey** [comment]
Try this: https://vod-secure.twitch.tv/c51263b576c710d7e70f_lowblowttv_39964504492_1605211367/chunked/index-dvr.m3u8.  Twitchtracker says the guy never streamed at 20:15 and that his latest stream was at 12:05. SO I assume that's what you're referring to. Also, use the vod id you find on twitch tracker, the last number in the URL: https://twitchtracker.com/lowblowttv/streams/39964504492. Is this the right link?

**Comment by Skallwar** [comment]
> Try this: https://vod-secure.twitch.tv/c51263b576c710d7e70f_lowblowttv_39964504492_1605211367/chunked/index-dvr.m3u8. 

You saved the day, thanks! :heart:

I was with him at 21:05 Paris time so it should have been 20:05 UTC time, no?
Your link (https://twitchtracker.com/lowblowttv/streams/39964504492) tell me the stream was at 20:02

> https://twitchtracker.com/lowblowttv/streams/39964504492. Is this the right link?

Yes indeed :+1:
