### ISSUE TITLE
stream ID and broadcast ID retrieval method needed

### ISSUE THREAD

**Issue by mystixa** [siddhantdubey/getdeletedtwitchvods#3]
The VOD ID that most people are familiar with would be the link to the web page. This being different from the 'broadcast id' thats required here. Would be good to make note of that in the readme possibly.

**Comment by siddhantdubey** [comment]
Hey sure, I'll be more clear about that. The broadcast id can be found in the last part of the URL on twitchtracker. For example https://twitchtracker.com/hasanabi/streams/40383779998, the broadcast id is 40383779998.
