### ISSUE TITLE
Not working for german channels?

### ISSUE THREAD

**Issue by duracell** [siddhantdubey/getdeletedtwitchvods#6]
Hey, I tried the Tool on different channels, because someone asked me to help them with recover their vod, but it's not working. After some Tests every english speaking channel I tried was working, every german channel (even the big one like papaplatte and montanabblack88) was not working.
Do you have any idea what could be the problem? I even tried different hour settings to check if it's a timezone problem.

**Comment by ChaosPaladin** [comment]
I think it cause because vods can keeps on some proxys, for RU streamers `https://d3c27h4odz752x.cloudfront.net/` instead `https://vod-secure.twitch.tv/`

**Comment by duracell** [comment]
Thanks, that helped!
